package com.cs206.cs206_g2t7fe;

public class Mrtlocations {

    //todo add array of mrt stations and their respecive locations
    public static String mrtstops[] = {
            // North-South Line
            "Jurong East",
            "Bukit Batok",
            "Bukit Gombak",
            "Choa Chu Kang",
            "Yew Tee",
            "Kranji",
            "Marsiling",
            "Woodlands",
            "Admiralty",
            "Sembawang",
            "Canberra",
            "Yishun",
            "Khatib",
            "Yio Chu Kang",
            "Ang Mo Kio",
            "Braddell",
            "Toa Payoh",
            "Novena",
            "Newton",
            "Orchard",
            "Somerset",
            "Dhoby Ghaut",
            "City Hall",
            "Raffles Place",
            "Marina Bay",
            "Marina South Pier",
            //east west
            "Pasir Ris",
            "Tampines",
            "Simei",
            "Tanah Merah",
            "Bedok",
            "Kembangan",
            "Eunos",
            "Paya Lebar",
            "Aljunied",
            "Kallang",
            "Lavender",
            "Bugis",
            "Tanjong Pagar",
            "Outram Park",
            "Tiong Bahru",
            "Redhill",
            "Queenstown",
            "Commonwealth",
            "Buona Vista",
            "Dover",
            "Clementi",
            "Chinese Garden",
            "Lakeside",
            "Boon Lay",
            "Pioneer",
            "Joo Koon",
            "Gul Circle",
            "Tuas Crescent",
            "Tuas West Road",
            "Tuas Link",
            "Expo",
            "Changi Airport",

            // Circle Line
            "Bras Basah",
            "Esplanade",
            "Promenade",
            "Nicoll Highway",
            "Stadium",
            "Mountbatten",
            "Dakota",
            "MacPherson",
            "Tai Seng",
            "Bartley",
            "Serangoon",
            "Lorong Chuan",
            "Bishan",
            "Marymount",
            "Caldecott",
            "Botanic Gardens",
            "Farrer Road",
            "Holland Village",
            "one-north",
            "Kent Ridge",
            "Haw Par Villa",
            "Pasir Panjang",
            "Labrador Park",
            "Telok Blangah",
            "HarbourFront"
    };

    public static  String[] getMrtList(){
        return mrtstops;
    }
}
